export default {
  SET_APP_LOADING: "SET_APP_LOADING",
  SET_KEY: "SET_KEY",
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",

  ADD_ENTITY: "ADD_ENTITY",
  SET_ENTITY_FOR_EDIT: "SET_ENTITY_FOR_EDIT",
  UPDATE_ENTITY: "UPDATE_ENTITY",
  DELETE_ENTITY: "DELETE_ENTITY",

  UPDATE_ENTITY_FORM_DATA: "UPDATE_ENTITY_FORM_DATA",
  CLEAR_ENTITY_FORM_DATA: "CLEAR_ENTITY_FORM_DATA",
};
